const userRoute = require('express').Router()
const UserController = require('../controllers/UserController')
const { authentication, isAdmin } = require('../middleware/authorization')
userRoute.get('/', authentication, isAdmin, UserController.getAllUsers)
userRoute.post('/', UserController.register)
userRoute.post('/login', UserController.login)
userRoute.patch('/update', authentication, UserController.update)
userRoute.delete('/', authentication, UserController.delete)
userRoute.get('/account', authentication, UserController.getUserById)
userRoute.post('/role/:id', authentication, isAdmin, UserController.updateRoleUser)
userRoute.post('/changepassword', authentication, UserController.changePassword)
module.exports = userRoute